[package]
name = "gameboy-emulator"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.14.1"
memmap2 = "0.9.4"

[dependencies.sdl2]
features = ["bundled"]
version = "0.36.0"
