#[derive(Debug)]
pub enum ArithmeticTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HL,
    D8,
}
#[derive(Debug)]
pub enum IncDecTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    Hli,
    BC,
    DE,
    HL,
    SP,
}
#[derive(Debug)]
pub enum ADDHLTarget {
    BC,
    DE,
    HL,
    SP,
}
#[derive(Debug)]
pub enum PrefixTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HL,
}
#[derive(Debug)]
pub enum BitPosition {
    B0,
    B1,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
}

impl std::convert::From<BitPosition> for u8 {
    fn from(position: BitPosition) -> u8 {
        match position {
            BitPosition::B0 => 0,
            BitPosition::B1 => 1,
            BitPosition::B2 => 2,
            BitPosition::B3 => 3,
            BitPosition::B4 => 4,
            BitPosition::B5 => 5,
            BitPosition::B6 => 6,
            BitPosition::B7 => 7,
        }
    }
}
#[derive(Debug)]
pub enum LoadByteTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HL,
}
#[derive(Debug)]
pub enum LoadByteSource {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    D8,
    HL,
}
#[derive(Debug)]
pub enum LoadWordTarget {
    BC,
    DE,
    HL,
    SP,
}
#[derive(Debug)]
pub enum IndirectTarget {
    BC,
    DE,
    Hli,
    Hld,
    Word,
    LastByte,
}
#[derive(Debug)]
pub enum StackTarget {
    AF,
    BC,
    DE,
    HL,
}
#[derive(Debug, PartialEq)]
pub enum JumpCondition {
    NotZero,
    Zero,
    NotCarry,
    Carry,
    Always,
}
#[derive(Debug)]
pub enum LoadType {
    Byte(LoadByteTarget, LoadByteSource),
    Word(LoadWordTarget),
    IndirectFromA(IndirectTarget),
    AFromIndirect(IndirectTarget),
    ByteAddressFromA,
    AFromByteAddress,
    IndirectFromSP,
    SPFromHL,
    HLFromSP,
}
#[derive(Debug)]
pub enum RSTLocation {
    X00,
    X08,
    X10,
    X18,
    X20,
    X28,
    X30,
    X38,
}

impl RSTLocation {
    pub fn to_hex(&self) -> u16 {
        match self {
            RSTLocation::X00 => 0x00,
            RSTLocation::X08 => 0x08,
            RSTLocation::X10 => 0x10,
            RSTLocation::X18 => 0x18,
            RSTLocation::X20 => 0x20,
            RSTLocation::X28 => 0x28,
            RSTLocation::X30 => 0x30,
            RSTLocation::X38 => 0x38,
        }
    }
}
#[derive(Debug)]
pub enum Instruction {
    // Arithmetic Operations
    Adc(ArithmeticTarget),
    Add(ArithmeticTarget),
    And(ArithmeticTarget),
    Cp(ArithmeticTarget),
    Or(ArithmeticTarget),
    Sbc(ArithmeticTarget),
    Sub(ArithmeticTarget),
    Xor(ArithmeticTarget),

    Dec(IncDecTarget),
    Inc(IncDecTarget),

    AddHl(ADDHLTarget),

    // Bit Operations
    Bit(PrefixTarget, BitPosition),
    Res(PrefixTarget, BitPosition),
    Set(PrefixTarget, BitPosition),
    Swap(PrefixTarget),

    // Bit Shift Operations
    Rl(PrefixTarget),
    Rla,
    Rlc(PrefixTarget),
    Rlca,
    Rr(PrefixTarget),
    Rra,
    Rrc(PrefixTarget),
    Rrca,
    Sla(PrefixTarget),
    Sra(PrefixTarget),
    Srl(PrefixTarget),

    // Load Operations
    Ld(LoadType),

    // Jumps and Subroutines
    Jp(JumpCondition),
    JpHl,
    Jr(JumpCondition),
    Call(JumpCondition),
    Ret(JumpCondition),
    Reti,
    Rst(RSTLocation),

    // Stack Operations
    AddSp,
    Pop(StackTarget),
    Push(StackTarget),

    // Misc Operations
    Ccf,
    Cpl,
    Daa,
    Di,
    Ei,
    Halt,
    Nop,
    Scf,
    // STOP,
}

impl Instruction {
    pub fn get_instruction(byte: u8, prefixed: bool) -> Instruction {
        if prefixed {
            Instruction::from_byte_prefixed(byte)
        } else {
            Instruction::from_byte(byte)
        }
    }

    fn from_byte_prefixed(byte: u8) -> Instruction {
        match byte {
            0x00 => Instruction::Rlc(PrefixTarget::B),
            0x01 => Instruction::Rlc(PrefixTarget::C),
            0x02 => Instruction::Rlc(PrefixTarget::D),
            0x03 => Instruction::Rlc(PrefixTarget::E),
            0x04 => Instruction::Rlc(PrefixTarget::H),
            0x05 => Instruction::Rlc(PrefixTarget::L),
            0x06 => Instruction::Rlc(PrefixTarget::HL),
            0x07 => Instruction::Rlc(PrefixTarget::A),
            0x08 => Instruction::Rrc(PrefixTarget::B),
            0x09 => Instruction::Rrc(PrefixTarget::C),
            0x0A => Instruction::Rrc(PrefixTarget::D),
            0x0B => Instruction::Rrc(PrefixTarget::E),
            0x0C => Instruction::Rrc(PrefixTarget::H),
            0x0D => Instruction::Rrc(PrefixTarget::L),
            0x0E => Instruction::Rrc(PrefixTarget::HL),
            0x0F => Instruction::Rrc(PrefixTarget::A),
            0x10 => Instruction::Rl(PrefixTarget::B),
            0x11 => Instruction::Rl(PrefixTarget::C),
            0x12 => Instruction::Rl(PrefixTarget::D),
            0x13 => Instruction::Rl(PrefixTarget::E),
            0x14 => Instruction::Rl(PrefixTarget::H),
            0x15 => Instruction::Rl(PrefixTarget::L),
            0x16 => Instruction::Rl(PrefixTarget::HL),
            0x17 => Instruction::Rl(PrefixTarget::A),
            0x18 => Instruction::Rr(PrefixTarget::B),
            0x19 => Instruction::Rr(PrefixTarget::C),
            0x1A => Instruction::Rr(PrefixTarget::D),
            0x1B => Instruction::Rr(PrefixTarget::E),
            0x1C => Instruction::Rr(PrefixTarget::H),
            0x1D => Instruction::Rr(PrefixTarget::L),
            0x1E => Instruction::Rr(PrefixTarget::HL),
            0x1F => Instruction::Rr(PrefixTarget::A),
            0x20 => Instruction::Sla(PrefixTarget::B),
            0x21 => Instruction::Sla(PrefixTarget::C),
            0x22 => Instruction::Sla(PrefixTarget::D),
            0x23 => Instruction::Sla(PrefixTarget::E),
            0x24 => Instruction::Sla(PrefixTarget::H),
            0x25 => Instruction::Sla(PrefixTarget::L),
            0x26 => Instruction::Sla(PrefixTarget::HL),
            0x27 => Instruction::Sla(PrefixTarget::A),
            0x28 => Instruction::Sra(PrefixTarget::B),
            0x29 => Instruction::Sra(PrefixTarget::C),
            0x2A => Instruction::Sra(PrefixTarget::D),
            0x2B => Instruction::Sra(PrefixTarget::E),
            0x2C => Instruction::Sra(PrefixTarget::H),
            0x2D => Instruction::Sra(PrefixTarget::L),
            0x2E => Instruction::Sra(PrefixTarget::HL),
            0x2F => Instruction::Sra(PrefixTarget::A),
            0x30 => Instruction::Swap(PrefixTarget::B),
            0x31 => Instruction::Swap(PrefixTarget::C),
            0x32 => Instruction::Swap(PrefixTarget::D),
            0x33 => Instruction::Swap(PrefixTarget::E),
            0x34 => Instruction::Swap(PrefixTarget::H),
            0x35 => Instruction::Swap(PrefixTarget::L),
            0x36 => Instruction::Swap(PrefixTarget::HL),
            0x37 => Instruction::Swap(PrefixTarget::A),
            0x38 => Instruction::Srl(PrefixTarget::B),
            0x39 => Instruction::Srl(PrefixTarget::C),
            0x3A => Instruction::Srl(PrefixTarget::D),
            0x3B => Instruction::Srl(PrefixTarget::E),
            0x3C => Instruction::Srl(PrefixTarget::H),
            0x3D => Instruction::Srl(PrefixTarget::L),
            0x3E => Instruction::Srl(PrefixTarget::HL),
            0x3F => Instruction::Srl(PrefixTarget::A),
            0x40 => Instruction::Bit(PrefixTarget::B, BitPosition::B0),
            0x41 => Instruction::Bit(PrefixTarget::C, BitPosition::B0),
            0x42 => Instruction::Bit(PrefixTarget::D, BitPosition::B0),
            0x43 => Instruction::Bit(PrefixTarget::E, BitPosition::B0),
            0x44 => Instruction::Bit(PrefixTarget::H, BitPosition::B0),
            0x45 => Instruction::Bit(PrefixTarget::L, BitPosition::B0),
            0x46 => Instruction::Bit(PrefixTarget::HL, BitPosition::B0),
            0x47 => Instruction::Bit(PrefixTarget::A, BitPosition::B0),
            0x48 => Instruction::Bit(PrefixTarget::B, BitPosition::B1),
            0x49 => Instruction::Bit(PrefixTarget::C, BitPosition::B1),
            0x4A => Instruction::Bit(PrefixTarget::D, BitPosition::B1),
            0x4B => Instruction::Bit(PrefixTarget::E, BitPosition::B1),
            0x4C => Instruction::Bit(PrefixTarget::H, BitPosition::B1),
            0x4D => Instruction::Bit(PrefixTarget::L, BitPosition::B1),
            0x4E => Instruction::Bit(PrefixTarget::HL, BitPosition::B1),
            0x4F => Instruction::Bit(PrefixTarget::A, BitPosition::B1),
            0x50 => Instruction::Bit(PrefixTarget::B, BitPosition::B2),
            0x51 => Instruction::Bit(PrefixTarget::C, BitPosition::B2),
            0x52 => Instruction::Bit(PrefixTarget::D, BitPosition::B2),
            0x53 => Instruction::Bit(PrefixTarget::E, BitPosition::B2),
            0x54 => Instruction::Bit(PrefixTarget::H, BitPosition::B2),
            0x55 => Instruction::Bit(PrefixTarget::L, BitPosition::B2),
            0x56 => Instruction::Bit(PrefixTarget::HL, BitPosition::B2),
            0x57 => Instruction::Bit(PrefixTarget::A, BitPosition::B2),
            0x58 => Instruction::Bit(PrefixTarget::B, BitPosition::B3),
            0x59 => Instruction::Bit(PrefixTarget::C, BitPosition::B3),
            0x5A => Instruction::Bit(PrefixTarget::D, BitPosition::B3),
            0x5B => Instruction::Bit(PrefixTarget::E, BitPosition::B3),
            0x5C => Instruction::Bit(PrefixTarget::H, BitPosition::B3),
            0x5D => Instruction::Bit(PrefixTarget::L, BitPosition::B3),
            0x5E => Instruction::Bit(PrefixTarget::HL, BitPosition::B3),
            0x5F => Instruction::Bit(PrefixTarget::A, BitPosition::B3),
            0x60 => Instruction::Bit(PrefixTarget::B, BitPosition::B4),
            0x61 => Instruction::Bit(PrefixTarget::C, BitPosition::B4),
            0x62 => Instruction::Bit(PrefixTarget::D, BitPosition::B4),
            0x63 => Instruction::Bit(PrefixTarget::E, BitPosition::B4),
            0x64 => Instruction::Bit(PrefixTarget::H, BitPosition::B4),
            0x65 => Instruction::Bit(PrefixTarget::L, BitPosition::B4),
            0x66 => Instruction::Bit(PrefixTarget::HL, BitPosition::B4),
            0x67 => Instruction::Bit(PrefixTarget::A, BitPosition::B4),
            0x68 => Instruction::Bit(PrefixTarget::B, BitPosition::B5),
            0x69 => Instruction::Bit(PrefixTarget::C, BitPosition::B5),
            0x6A => Instruction::Bit(PrefixTarget::D, BitPosition::B5),
            0x6B => Instruction::Bit(PrefixTarget::E, BitPosition::B5),
            0x6C => Instruction::Bit(PrefixTarget::H, BitPosition::B5),
            0x6D => Instruction::Bit(PrefixTarget::L, BitPosition::B5),
            0x6E => Instruction::Bit(PrefixTarget::HL, BitPosition::B5),
            0x6F => Instruction::Bit(PrefixTarget::A, BitPosition::B5),
            0x70 => Instruction::Bit(PrefixTarget::B, BitPosition::B6),
            0x71 => Instruction::Bit(PrefixTarget::C, BitPosition::B6),
            0x72 => Instruction::Bit(PrefixTarget::D, BitPosition::B6),
            0x73 => Instruction::Bit(PrefixTarget::E, BitPosition::B6),
            0x74 => Instruction::Bit(PrefixTarget::H, BitPosition::B6),
            0x75 => Instruction::Bit(PrefixTarget::L, BitPosition::B6),
            0x76 => Instruction::Bit(PrefixTarget::HL, BitPosition::B6),
            0x77 => Instruction::Bit(PrefixTarget::A, BitPosition::B6),
            0x78 => Instruction::Bit(PrefixTarget::B, BitPosition::B7),
            0x79 => Instruction::Bit(PrefixTarget::C, BitPosition::B7),
            0x7A => Instruction::Bit(PrefixTarget::D, BitPosition::B7),
            0x7B => Instruction::Bit(PrefixTarget::E, BitPosition::B7),
            0x7C => Instruction::Bit(PrefixTarget::H, BitPosition::B7),
            0x7D => Instruction::Bit(PrefixTarget::L, BitPosition::B7),
            0x7E => Instruction::Bit(PrefixTarget::HL, BitPosition::B7),
            0x7F => Instruction::Bit(PrefixTarget::A, BitPosition::B7),
            0x80 => Instruction::Res(PrefixTarget::B, BitPosition::B0),
            0x81 => Instruction::Res(PrefixTarget::C, BitPosition::B0),
            0x82 => Instruction::Res(PrefixTarget::D, BitPosition::B0),
            0x83 => Instruction::Res(PrefixTarget::E, BitPosition::B0),
            0x84 => Instruction::Res(PrefixTarget::H, BitPosition::B0),
            0x85 => Instruction::Res(PrefixTarget::L, BitPosition::B0),
            0x86 => Instruction::Res(PrefixTarget::HL, BitPosition::B0),
            0x87 => Instruction::Res(PrefixTarget::A, BitPosition::B0),
            0x88 => Instruction::Res(PrefixTarget::B, BitPosition::B1),
            0x89 => Instruction::Res(PrefixTarget::C, BitPosition::B1),
            0x8A => Instruction::Res(PrefixTarget::D, BitPosition::B1),
            0x8B => Instruction::Res(PrefixTarget::E, BitPosition::B1),
            0x8C => Instruction::Res(PrefixTarget::H, BitPosition::B1),
            0x8D => Instruction::Res(PrefixTarget::L, BitPosition::B1),
            0x8E => Instruction::Res(PrefixTarget::HL, BitPosition::B1),
            0x8F => Instruction::Res(PrefixTarget::A, BitPosition::B1),
            0x90 => Instruction::Res(PrefixTarget::B, BitPosition::B2),
            0x91 => Instruction::Res(PrefixTarget::C, BitPosition::B2),
            0x92 => Instruction::Res(PrefixTarget::D, BitPosition::B2),
            0x93 => Instruction::Res(PrefixTarget::E, BitPosition::B2),
            0x94 => Instruction::Res(PrefixTarget::H, BitPosition::B2),
            0x95 => Instruction::Res(PrefixTarget::L, BitPosition::B2),
            0x96 => Instruction::Res(PrefixTarget::HL, BitPosition::B2),
            0x97 => Instruction::Res(PrefixTarget::A, BitPosition::B2),
            0x98 => Instruction::Res(PrefixTarget::B, BitPosition::B3),
            0x99 => Instruction::Res(PrefixTarget::C, BitPosition::B3),
            0x9A => Instruction::Res(PrefixTarget::D, BitPosition::B3),
            0x9B => Instruction::Res(PrefixTarget::E, BitPosition::B3),
            0x9C => Instruction::Res(PrefixTarget::H, BitPosition::B3),
            0x9D => Instruction::Res(PrefixTarget::L, BitPosition::B3),
            0x9E => Instruction::Res(PrefixTarget::HL, BitPosition::B3),
            0x9F => Instruction::Res(PrefixTarget::A, BitPosition::B3),
            0xA0 => Instruction::Res(PrefixTarget::B, BitPosition::B4),
            0xA1 => Instruction::Res(PrefixTarget::C, BitPosition::B4),
            0xA2 => Instruction::Res(PrefixTarget::D, BitPosition::B4),
            0xA3 => Instruction::Res(PrefixTarget::E, BitPosition::B4),
            0xA4 => Instruction::Res(PrefixTarget::H, BitPosition::B4),
            0xA5 => Instruction::Res(PrefixTarget::L, BitPosition::B4),
            0xA6 => Instruction::Res(PrefixTarget::HL, BitPosition::B4),
            0xA7 => Instruction::Res(PrefixTarget::A, BitPosition::B4),
            0xA8 => Instruction::Res(PrefixTarget::B, BitPosition::B5),
            0xA9 => Instruction::Res(PrefixTarget::C, BitPosition::B5),
            0xAA => Instruction::Res(PrefixTarget::D, BitPosition::B5),
            0xAB => Instruction::Res(PrefixTarget::E, BitPosition::B5),
            0xAC => Instruction::Res(PrefixTarget::H, BitPosition::B5),
            0xAD => Instruction::Res(PrefixTarget::L, BitPosition::B5),
            0xAE => Instruction::Res(PrefixTarget::HL, BitPosition::B5),
            0xAF => Instruction::Res(PrefixTarget::A, BitPosition::B5),
            0xB0 => Instruction::Res(PrefixTarget::B, BitPosition::B6),
            0xB1 => Instruction::Res(PrefixTarget::C, BitPosition::B6),
            0xB2 => Instruction::Res(PrefixTarget::D, BitPosition::B6),
            0xB3 => Instruction::Res(PrefixTarget::E, BitPosition::B6),
            0xB4 => Instruction::Res(PrefixTarget::H, BitPosition::B6),
            0xB5 => Instruction::Res(PrefixTarget::L, BitPosition::B6),
            0xB6 => Instruction::Res(PrefixTarget::HL, BitPosition::B6),
            0xB7 => Instruction::Res(PrefixTarget::A, BitPosition::B6),
            0xB8 => Instruction::Res(PrefixTarget::B, BitPosition::B7),
            0xB9 => Instruction::Res(PrefixTarget::C, BitPosition::B7),
            0xBA => Instruction::Res(PrefixTarget::D, BitPosition::B7),
            0xBB => Instruction::Res(PrefixTarget::E, BitPosition::B7),
            0xBC => Instruction::Res(PrefixTarget::H, BitPosition::B7),
            0xBD => Instruction::Res(PrefixTarget::L, BitPosition::B7),
            0xBE => Instruction::Res(PrefixTarget::HL, BitPosition::B7),
            0xBF => Instruction::Res(PrefixTarget::A, BitPosition::B7),
            0xC0 => Instruction::Set(PrefixTarget::B, BitPosition::B0),
            0xC1 => Instruction::Set(PrefixTarget::C, BitPosition::B0),
            0xC2 => Instruction::Set(PrefixTarget::D, BitPosition::B0),
            0xC3 => Instruction::Set(PrefixTarget::E, BitPosition::B0),
            0xC4 => Instruction::Set(PrefixTarget::H, BitPosition::B0),
            0xC5 => Instruction::Set(PrefixTarget::L, BitPosition::B0),
            0xC6 => Instruction::Set(PrefixTarget::HL, BitPosition::B0),
            0xC7 => Instruction::Set(PrefixTarget::A, BitPosition::B0),
            0xC8 => Instruction::Set(PrefixTarget::B, BitPosition::B1),
            0xC9 => Instruction::Set(PrefixTarget::C, BitPosition::B1),
            0xCA => Instruction::Set(PrefixTarget::D, BitPosition::B1),
            0xCB => Instruction::Set(PrefixTarget::E, BitPosition::B1),
            0xCC => Instruction::Set(PrefixTarget::H, BitPosition::B1),
            0xCD => Instruction::Set(PrefixTarget::L, BitPosition::B1),
            0xCE => Instruction::Set(PrefixTarget::HL, BitPosition::B1),
            0xCF => Instruction::Set(PrefixTarget::A, BitPosition::B1),
            0xD0 => Instruction::Set(PrefixTarget::B, BitPosition::B2),
            0xD1 => Instruction::Set(PrefixTarget::C, BitPosition::B2),
            0xD2 => Instruction::Set(PrefixTarget::D, BitPosition::B2),
            0xD3 => Instruction::Set(PrefixTarget::E, BitPosition::B2),
            0xD4 => Instruction::Set(PrefixTarget::H, BitPosition::B2),
            0xD5 => Instruction::Set(PrefixTarget::L, BitPosition::B2),
            0xD6 => Instruction::Set(PrefixTarget::HL, BitPosition::B2),
            0xD7 => Instruction::Set(PrefixTarget::A, BitPosition::B2),
            0xD8 => Instruction::Set(PrefixTarget::B, BitPosition::B3),
            0xD9 => Instruction::Set(PrefixTarget::C, BitPosition::B3),
            0xDA => Instruction::Set(PrefixTarget::D, BitPosition::B3),
            0xDB => Instruction::Set(PrefixTarget::E, BitPosition::B3),
            0xDC => Instruction::Set(PrefixTarget::H, BitPosition::B3),
            0xDD => Instruction::Set(PrefixTarget::L, BitPosition::B3),
            0xDE => Instruction::Set(PrefixTarget::HL, BitPosition::B3),
            0xDF => Instruction::Set(PrefixTarget::A, BitPosition::B3),
            0xE0 => Instruction::Set(PrefixTarget::B, BitPosition::B4),
            0xE1 => Instruction::Set(PrefixTarget::C, BitPosition::B4),
            0xE2 => Instruction::Set(PrefixTarget::D, BitPosition::B4),
            0xE3 => Instruction::Set(PrefixTarget::E, BitPosition::B4),
            0xE4 => Instruction::Set(PrefixTarget::H, BitPosition::B4),
            0xE5 => Instruction::Set(PrefixTarget::L, BitPosition::B4),
            0xE6 => Instruction::Set(PrefixTarget::HL, BitPosition::B4),
            0xE7 => Instruction::Set(PrefixTarget::A, BitPosition::B4),
            0xE8 => Instruction::Set(PrefixTarget::B, BitPosition::B5),
            0xE9 => Instruction::Set(PrefixTarget::C, BitPosition::B5),
            0xEA => Instruction::Set(PrefixTarget::D, BitPosition::B5),
            0xEB => Instruction::Set(PrefixTarget::E, BitPosition::B5),
            0xEC => Instruction::Set(PrefixTarget::H, BitPosition::B5),
            0xED => Instruction::Set(PrefixTarget::L, BitPosition::B5),
            0xEE => Instruction::Set(PrefixTarget::HL, BitPosition::B5),
            0xEF => Instruction::Set(PrefixTarget::A, BitPosition::B5),
            0xF0 => Instruction::Set(PrefixTarget::B, BitPosition::B6),
            0xF1 => Instruction::Set(PrefixTarget::C, BitPosition::B6),
            0xF2 => Instruction::Set(PrefixTarget::D, BitPosition::B6),
            0xF3 => Instruction::Set(PrefixTarget::E, BitPosition::B6),
            0xF4 => Instruction::Set(PrefixTarget::H, BitPosition::B6),
            0xF5 => Instruction::Set(PrefixTarget::L, BitPosition::B6),
            0xF6 => Instruction::Set(PrefixTarget::HL, BitPosition::B6),
            0xF7 => Instruction::Set(PrefixTarget::A, BitPosition::B6),
            0xF8 => Instruction::Set(PrefixTarget::B, BitPosition::B7),
            0xF9 => Instruction::Set(PrefixTarget::C, BitPosition::B7),
            0xFA => Instruction::Set(PrefixTarget::D, BitPosition::B7),
            0xFB => Instruction::Set(PrefixTarget::E, BitPosition::B7),
            0xFC => Instruction::Set(PrefixTarget::H, BitPosition::B7),
            0xFD => Instruction::Set(PrefixTarget::L, BitPosition::B7),
            0xFE => Instruction::Set(PrefixTarget::HL, BitPosition::B7),
            0xFF => Instruction::Set(PrefixTarget::A, BitPosition::B7),
        }
    }

    fn from_byte(byte: u8) -> Instruction {
        match byte {
            0x00 => Instruction::Nop,
            0x01 => Instruction::Ld(LoadType::Word(LoadWordTarget::BC)),
            0x02 => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::BC)),
            0x03 => Instruction::Inc(IncDecTarget::BC),
            0x04 => Instruction::Inc(IncDecTarget::B),
            0x05 => Instruction::Dec(IncDecTarget::B),
            0x06 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::D8)),
            0x07 => Instruction::Rlca,
            0x08 => Instruction::Ld(LoadType::IndirectFromSP),
            0x09 => Instruction::AddHl(ADDHLTarget::BC),
            0x0A => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::BC)),
            0x0B => Instruction::Dec(IncDecTarget::BC),
            0x0C => Instruction::Inc(IncDecTarget::C),
            0x0D => Instruction::Dec(IncDecTarget::C),
            0x0E => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::D8)),
            0x0F => Instruction::Rrca,
            // 0x10 => Instruction::STOP,
            0x11 => Instruction::Ld(LoadType::Word(LoadWordTarget::DE)),
            0x12 => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::DE)),
            0x13 => Instruction::Inc(IncDecTarget::DE),
            0x14 => Instruction::Inc(IncDecTarget::D),
            0x15 => Instruction::Dec(IncDecTarget::D),
            0x16 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::D8)),
            0x17 => Instruction::Rla,
            0x18 => Instruction::Jr(JumpCondition::Always),
            0x19 => Instruction::AddHl(ADDHLTarget::DE),
            0x1A => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::DE)),
            0x1B => Instruction::Dec(IncDecTarget::DE),
            0x1C => Instruction::Inc(IncDecTarget::E),
            0x1D => Instruction::Dec(IncDecTarget::E),
            0x1E => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::D8)),
            0x1F => Instruction::Rra,
            0x20 => Instruction::Jr(JumpCondition::NotZero),
            0x21 => Instruction::Ld(LoadType::Word(LoadWordTarget::HL)),
            0x22 => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::Hli)),
            0x23 => Instruction::Inc(IncDecTarget::HL),
            0x24 => Instruction::Inc(IncDecTarget::H),
            0x25 => Instruction::Dec(IncDecTarget::H),
            0x26 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::D8)),
            0x27 => Instruction::Daa,
            0x28 => Instruction::Jr(JumpCondition::Zero),
            0x29 => Instruction::AddHl(ADDHLTarget::HL),
            0x2A => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::Hli)),
            0x2B => Instruction::Dec(IncDecTarget::HL),
            0x2C => Instruction::Inc(IncDecTarget::L),
            0x2D => Instruction::Dec(IncDecTarget::L),
            0x2E => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::D8)),
            0x2F => Instruction::Cpl,
            0x30 => Instruction::Jr(JumpCondition::NotCarry),
            0x31 => Instruction::Ld(LoadType::Word(LoadWordTarget::SP)),
            0x32 => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::Hld)),
            0x33 => Instruction::Inc(IncDecTarget::SP),
            0x34 => Instruction::Inc(IncDecTarget::Hli),
            0x35 => Instruction::Dec(IncDecTarget::Hli),
            0x36 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::D8)),
            0x37 => Instruction::Scf,
            0x38 => Instruction::Jr(JumpCondition::Carry),
            0x39 => Instruction::AddHl(ADDHLTarget::SP),
            0x3A => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::Hld)),
            0x3B => Instruction::Dec(IncDecTarget::SP),
            0x3C => Instruction::Inc(IncDecTarget::A),
            0x3D => Instruction::Dec(IncDecTarget::A),
            0x3E => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::D8)),
            0x3F => Instruction::Ccf,
            0x40 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::B)),
            0x41 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::C)),
            0x42 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::D)),
            0x43 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::E)),
            0x44 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::H)),
            0x45 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::L)),
            0x46 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::HL)),
            0x47 => Instruction::Ld(LoadType::Byte(LoadByteTarget::B, LoadByteSource::A)),
            0x48 => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::B)),
            0x49 => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::C)),
            0x4A => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::D)),
            0x4B => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::E)),
            0x4C => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::H)),
            0x4D => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::L)),
            0x4E => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::HL)),
            0x4F => Instruction::Ld(LoadType::Byte(LoadByteTarget::C, LoadByteSource::A)),
            0x50 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::B)),
            0x51 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::C)),
            0x52 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::D)),
            0x53 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::E)),
            0x54 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::H)),
            0x55 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::L)),
            0x56 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::HL)),
            0x57 => Instruction::Ld(LoadType::Byte(LoadByteTarget::D, LoadByteSource::A)),
            0x58 => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::B)),
            0x59 => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::C)),
            0x5A => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::D)),
            0x5B => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::E)),
            0x5C => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::H)),
            0x5D => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::L)),
            0x5E => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::HL)),
            0x5F => Instruction::Ld(LoadType::Byte(LoadByteTarget::E, LoadByteSource::A)),
            0x60 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::B)),
            0x61 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::C)),
            0x62 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::D)),
            0x63 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::E)),
            0x64 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::H)),
            0x65 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::L)),
            0x66 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::HL)),
            0x67 => Instruction::Ld(LoadType::Byte(LoadByteTarget::H, LoadByteSource::A)),
            0x68 => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::B)),
            0x69 => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::C)),
            0x6A => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::D)),
            0x6B => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::E)),
            0x6C => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::H)),
            0x6D => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::L)),
            0x6E => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::HL)),
            0x6F => Instruction::Ld(LoadType::Byte(LoadByteTarget::L, LoadByteSource::A)),
            0x70 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::B)),
            0x71 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::C)),
            0x72 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::D)),
            0x73 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::E)),
            0x74 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::H)),
            0x75 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::L)),
            0x76 => Instruction::Halt,
            0x77 => Instruction::Ld(LoadType::Byte(LoadByteTarget::HL, LoadByteSource::A)),
            0x78 => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::B)),
            0x79 => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::C)),
            0x7A => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::D)),
            0x7B => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::E)),
            0x7C => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::H)),
            0x7D => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::L)),
            0x7E => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::HL)),
            0x7F => Instruction::Ld(LoadType::Byte(LoadByteTarget::A, LoadByteSource::A)),
            0x80 => Instruction::Add(ArithmeticTarget::B),
            0x81 => Instruction::Add(ArithmeticTarget::C),
            0x82 => Instruction::Add(ArithmeticTarget::D),
            0x83 => Instruction::Add(ArithmeticTarget::E),
            0x84 => Instruction::Add(ArithmeticTarget::H),
            0x85 => Instruction::Add(ArithmeticTarget::L),
            0x86 => Instruction::Add(ArithmeticTarget::HL),
            0x87 => Instruction::Add(ArithmeticTarget::A),
            0x88 => Instruction::Adc(ArithmeticTarget::B),
            0x89 => Instruction::Adc(ArithmeticTarget::C),
            0x8A => Instruction::Adc(ArithmeticTarget::D),
            0x8B => Instruction::Adc(ArithmeticTarget::E),
            0x8C => Instruction::Adc(ArithmeticTarget::H),
            0x8D => Instruction::Adc(ArithmeticTarget::L),
            0x8E => Instruction::Adc(ArithmeticTarget::HL),
            0x8F => Instruction::Adc(ArithmeticTarget::A),
            0x90 => Instruction::Sub(ArithmeticTarget::B),
            0x91 => Instruction::Sub(ArithmeticTarget::C),
            0x92 => Instruction::Sub(ArithmeticTarget::D),
            0x93 => Instruction::Sub(ArithmeticTarget::E),
            0x94 => Instruction::Sub(ArithmeticTarget::H),
            0x95 => Instruction::Sub(ArithmeticTarget::L),
            0x96 => Instruction::Sub(ArithmeticTarget::HL),
            0x97 => Instruction::Sub(ArithmeticTarget::A),
            0x98 => Instruction::Sbc(ArithmeticTarget::B),
            0x99 => Instruction::Sbc(ArithmeticTarget::C),
            0x9A => Instruction::Sbc(ArithmeticTarget::D),
            0x9B => Instruction::Sbc(ArithmeticTarget::E),
            0x9C => Instruction::Sbc(ArithmeticTarget::H),
            0x9D => Instruction::Sbc(ArithmeticTarget::L),
            0x9E => Instruction::Sbc(ArithmeticTarget::HL),
            0x9F => Instruction::Sbc(ArithmeticTarget::A),
            0xA0 => Instruction::And(ArithmeticTarget::B),
            0xA1 => Instruction::And(ArithmeticTarget::C),
            0xA2 => Instruction::And(ArithmeticTarget::D),
            0xA3 => Instruction::And(ArithmeticTarget::E),
            0xA4 => Instruction::And(ArithmeticTarget::H),
            0xA5 => Instruction::And(ArithmeticTarget::L),
            0xA6 => Instruction::And(ArithmeticTarget::HL),
            0xA7 => Instruction::And(ArithmeticTarget::A),
            0xA8 => Instruction::Xor(ArithmeticTarget::B),
            0xA9 => Instruction::Xor(ArithmeticTarget::C),
            0xAA => Instruction::Xor(ArithmeticTarget::D),
            0xAB => Instruction::Xor(ArithmeticTarget::E),
            0xAC => Instruction::Xor(ArithmeticTarget::H),
            0xAD => Instruction::Xor(ArithmeticTarget::L),
            0xAE => Instruction::Xor(ArithmeticTarget::HL),
            0xAF => Instruction::Xor(ArithmeticTarget::A),
            0xB0 => Instruction::Or(ArithmeticTarget::B),
            0xB1 => Instruction::Or(ArithmeticTarget::C),
            0xB2 => Instruction::Or(ArithmeticTarget::D),
            0xB3 => Instruction::Or(ArithmeticTarget::E),
            0xB4 => Instruction::Or(ArithmeticTarget::H),
            0xB5 => Instruction::Or(ArithmeticTarget::L),
            0xB6 => Instruction::Or(ArithmeticTarget::HL),
            0xB7 => Instruction::Or(ArithmeticTarget::A),
            0xB8 => Instruction::Cp(ArithmeticTarget::B),
            0xB9 => Instruction::Cp(ArithmeticTarget::C),
            0xBA => Instruction::Cp(ArithmeticTarget::D),
            0xBB => Instruction::Cp(ArithmeticTarget::E),
            0xBC => Instruction::Cp(ArithmeticTarget::H),
            0xBD => Instruction::Cp(ArithmeticTarget::L),
            0xBE => Instruction::Cp(ArithmeticTarget::HL),
            0xBF => Instruction::Cp(ArithmeticTarget::A),
            0xC0 => Instruction::Ret(JumpCondition::NotZero),
            0xC1 => Instruction::Pop(StackTarget::BC),
            0xC2 => Instruction::Jp(JumpCondition::NotZero),
            0xC3 => Instruction::Jp(JumpCondition::Always),
            0xC4 => Instruction::Call(JumpCondition::NotZero),
            0xC5 => Instruction::Push(StackTarget::BC),
            0xC6 => Instruction::Add(ArithmeticTarget::D8),
            0xC7 => Instruction::Rst(RSTLocation::X00),
            0xC8 => Instruction::Ret(JumpCondition::Zero),
            0xC9 => Instruction::Ret(JumpCondition::Always),
            0xCA => Instruction::Jp(JumpCondition::Zero),

            0xCC => Instruction::Call(JumpCondition::Zero),
            0xCD => Instruction::Call(JumpCondition::Always),
            0xCE => Instruction::Adc(ArithmeticTarget::D8),
            0xCF => Instruction::Rst(RSTLocation::X08),
            0xD0 => Instruction::Ret(JumpCondition::NotCarry),
            0xD1 => Instruction::Pop(StackTarget::DE),
            0xD2 => Instruction::Jp(JumpCondition::NotCarry),
            0xD4 => Instruction::Call(JumpCondition::NotCarry),
            0xD5 => Instruction::Push(StackTarget::DE),
            0xD6 => Instruction::Sub(ArithmeticTarget::D8),
            0xD7 => Instruction::Rst(RSTLocation::X10),
            0xD8 => Instruction::Ret(JumpCondition::Carry),
            0xD9 => Instruction::Reti,
            0xDA => Instruction::Jp(JumpCondition::Carry),
            0xDC => Instruction::Call(JumpCondition::Carry),
            0xDE => Instruction::Sbc(ArithmeticTarget::D8),
            0xDF => Instruction::Rst(RSTLocation::X18),
            0xE0 => Instruction::Ld(LoadType::ByteAddressFromA),
            0xE1 => Instruction::Pop(StackTarget::HL),
            0xE2 => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::LastByte)),
            0xE5 => Instruction::Push(StackTarget::HL),
            0xE6 => Instruction::And(ArithmeticTarget::D8),
            0xE7 => Instruction::Rst(RSTLocation::X20),
            0xE8 => Instruction::AddSp,
            0xE9 => Instruction::JpHl,
            0xEA => Instruction::Ld(LoadType::IndirectFromA(IndirectTarget::Word)),
            0xEE => Instruction::Xor(ArithmeticTarget::D8),
            0xEF => Instruction::Rst(RSTLocation::X28),
            0xF0 => Instruction::Ld(LoadType::AFromByteAddress),
            0xF1 => Instruction::Pop(StackTarget::AF),
            0xF2 => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::LastByte)),
            0xF3 => Instruction::Di,
            0xF5 => Instruction::Push(StackTarget::AF),
            0xF6 => Instruction::Or(ArithmeticTarget::D8),
            0xF7 => Instruction::Rst(RSTLocation::X30),
            0xF8 => Instruction::Ld(LoadType::HLFromSP),
            0xF9 => Instruction::Ld(LoadType::SPFromHL),
            0xFA => Instruction::Ld(LoadType::AFromIndirect(IndirectTarget::Word)),
            0xFB => Instruction::Ei,
            0xFE => Instruction::Cp(ArithmeticTarget::D8),
            0xFF => Instruction::Rst(RSTLocation::X38),
            _ => Instruction::Nop,
        }
    }
}
